### PR TITLE
Check text length before sending a ask for message splitting

### LINKED ISSUE #48: Threema should provide more explicit error message for large messages
When I send a large message to another user, it does not work.
Probably Threema should show how large a message may be.

I get the following error message:
Screenshot

That's the text I sent:
```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. 

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. 

Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. 

Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 

Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis. 

At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, At accusam aliquyam diam diam dolore dolores duo eirmod eos erat, et nonumy sed tempor et et invidunt justo labore Stet clita ea et gubergren, kasd magna no rebum. sanctus sea sed takimata ut vero voluptua. est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat. 

Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus. 

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

### PR DESCRIPTION
**Pull request by sillych**
After entering a too long text (>3500 Bytes)

2017-02-21-171317_1066x185_scrot

Fixes #48 

Threema Web ask for splitting this message into x messages

2017-02-21-171406_753x249_scrot

Confirming split the message into x messages

2017-02-21-171424_1037x813_scrot

**Aborting** this process do **not delete the entered message** in the compose area

### CODE REVIEW

File: src/directives/compose_area.ts [hunk 1]
```diff
@@ -121,26 +126,63 @@ export default [
                                 $log.warn(logTag, 'Unhandled node:', node);
                         }
                     }
-                    const textMessageData: threema.TextMessageData = {text: text.trim()};
-                    // send as array
-                    return scope.submit('text', [textMessageData]);
+                    return new Promise((resolve, reject) => {
+                        let submitTexts = (strings: string[]) => {
+                            let messages: threema.TextMessageData[] = [];
+                            strings.forEach((piece: string) => {
```
Comment (dbrgn) [inline src/directives/compose_area.ts]: This *could* be replaced with an ES2015 loop:

```javascript
for (let piece of strings) {
    messages.push({
        text: piece,
    });
}
```

File: src/directives/compose_area.ts [hunk 2]
```diff
@@ -121,26 +126,63 @@ export default [
...
+                                messages.push({
+                                    text: piece,
+                                } as threema.TextMessageData);
+                            });
+                            scope.submit('text', messages)
+                                .then(() => {
+                                    resolve();
+                                })
```
Comment (dbrgn) [inline src/directives/compose_area.ts]: I think this could be simplified to `.then(resolve)`. Same thing on the next line (`catch(reject)`) and line 160 (`}, reject);`).

File: src/directives/compose_area.ts [hunk 3]
```diff
@@ -121,26 +126,63 @@ export default [
...
                             scope.stopTyping();
 
                             scope.onTyping('');
-                        }
 
-                        updateView();
-                        return submitted;
+                            updateView();
+                        }).catch(() => {
+                            // do nothing
```
Comment (dbrgn) [inline src/directives/compose_area.ts]: Maybe this should be logged as a warning.

File: src/directives/compose_area.ts [hunk 4]
```diff
@@ -121,26 +126,63 @@ export default [
...
+                                    resolve();
+                                })
+                                .catch((error) => {
+                                    reject(error);
+                                });
+                        };
+
+                        let fullText = text.trim();
+                        if (fullText.length > scope.maxTextLength) {
+                            let pieces: string[] = stringService.byteChunk(fullText, scope.maxTextLength, 20);
```
Comment (dbrgn) [inline src/directives/compose_area.ts]: Maybe 50 would be better as default offset, to prevent splitting long words? (The default could also be changed directly in the string service...)

File: src/services/string.ts [hunk 5]
```diff
@@ -0,0 +1,166 @@
...
+
+        let chunks = [];
+        // append a separator
+        let rest = str + ' ';
+        do {
+            let piece = rest.substring(0, length + (offset > 0 ? 1 : 0));
+
+            // check if the split-position is valid (not in breaking emoji)
+            if (!isValidPosition(piece, piece.length - 1)) {
+                piece = piece.substring(0, piece.length - 1);
```
Comment (dbrgn) [inline src/services/string.ts]: This could break 4 byte characters, right? 😕

File: src/services/string.ts [hunk 6]
```diff
@@ -0,0 +1,166 @@
...
+
+            // trim piece
+            piece = piece.trim();
+
+            if (piece.length > 0) {
+                chunks.push(piece);
+                // cut and trim the rest
+                rest = rest.substring(piece.length).trim();
+            } else {
+                // abort, should not happen
```
Comment (dbrgn) [inline src/services/string.ts]: Maybe log a warning?

File: src/services/string.ts [hunk 7]
```diff
@@ -0,0 +1,166 @@
...
+
+export class StringService implements threema.StringService {
+
+    /**
+     * Split a string into chunks
+     * @param str the string to chunk
+     * @param length max length of a chuck
+     * @param offset searching for a separator in the given offset, 0 disable separator indexing
+     */
+    public chunk(str: string, length: number, offset: number = 10): string[] {
```
Comment (dbrgn) [inline src/services/string.ts]: Could it be that this isn't actually being used right now? The submitText() method uses `byteChunk`.

**Comment by lgrahl** [comment]
Small nit: It should be *No more than ...*

File: src/services/string.ts (hunk 7 above)
Comment (sillych) [inline src/services/string.ts]: Good catch :+1:

File: src/services/string.ts (hunk 5 above)
Comment (sillych) [inline src/services/string.ts]: Correct, `chunk` will be removed

File: src/services/string.ts (hunk 6 above)
Comment (sillych) [inline src/services/string.ts]: obsolete

File: src/directives/compose_area.ts (hunk 3 above)
Comment (sillych) [inline src/directives/compose_area.ts]: :+1:

File: src/directives/compose_area.ts (hunk 4 above)
Comment (sillych) [inline src/directives/compose_area.ts]: :+1:

File: src/directives/compose_area.ts (hunk 2 above)
Comment (sillych) [inline src/directives/compose_area.ts]: smart :fox_face:

File: src/directives/compose_area.ts (hunk 1 above)
Comment (sillych) [inline src/directives/compose_area.ts]: *creature of habit*

File: src/services/string.ts [hunk 8]
```diff
@@ -0,0 +1,62 @@
...
+        let offsetChars = [' ', '\r', '\n', '\t', '.'];
+        let lastSeparator = -1;
+        chars.forEach ((charString: string) => {
+            let length = Buffer.byteLength(charString, 'utf8');
+            if (offset !== null) {
+                if (offsetChars.indexOf(charString) > -1) {
+                    lastSeparator = currentChunkSize + 1;
+                }
+            }
+            // console.log(charString, length);
```
Comment (dbrgn) [inline src/services/string.ts]: Dead code :)
