### PR TITLE
Fix sending files and pictures to distribution lists

### LINKED ISSUE #394: Sending pictures to distribution lists won't work
## Expected Behavior
When sending pictures to a distribution list created in the threema app, the pictures should be send to all members of this list.

## Current Behavior
Sending pictures through the web client to distribution lists is not working. 

## Steps to Reproduce (for bugs)
1. Create a distribution list on threema
2. Log in to the web client
3. Send a picture to the newly created distribution list through the web client

## Your Environment
* Threema Web version: 1.7.0
* Threema for Android version: 3.3.2000391
* Threema for Android source: Play Store
* Browser name and version: Chromium 62.0.3202.94
* Operating system and version: Manjaro Linux 17.0.6

### PR DESCRIPTION
**Pull request by dbrgn**
Fixes #394.

### CODE REVIEW

File: src/services/webclient.ts [hunk 1]
```diff
@@ -1752,18 +1752,29 @@ export class WebClientService {
...
+                                        const distributionList = this.distributionLists.get(receiver.id);
+                                        if (distributionList === undefined) {
+                                            this.log.error(`Distribution list ${receiver.id} not found`);
+                                            return reject(this.$translate.instant('error.ERROR_OCCURRED'));
+                                        }
+                                        members = distributionList.members;
+                                        break;
                                 }
-                                group.members.forEach((identity: string) => {
+                                members.forEach((identity: string) => {
```
Comment (lgrahl) [inline src/services/webclient.ts]: Any reason to not make this is a normal `for`?

Comment (dbrgn) [reply src/services/webclient.ts]: I don't think so. I'll change it.
