### PR TITLE
Harmonize status icons

### LINKED ISSUE #345: Gateway ID message status still shown in chat list
## Expected Behavior

As in the app the chat list should not have icons for received/sent/… for Gateway IDs.

## Current Behavior

The chat itself has no icons, but in the chat list they are there.

## Steps to Reproduce (for bugs)

1. Send a message to *SUPPORT, e.g.
2. You will see the ✉️ icon in the chat list.

## Your Environment

* Threema Web version: 1.5.0-gh

### PR DESCRIPTION
**Pull request by sillych**
fix #345

### CODE REVIEW

File: src/directives/latest_message.ts [hunk 1]
```diff
@@ -52,8 +53,21 @@ export default [
...
+                if (this.showVoipInfo) {
+                    this.statusIcon = 'phone_locked';
+                } else if (this.isGroup) {
+                    this.statusIcon = 'group';
+                } else if (this.isDistributionList) {
+                    this.statusIcon = 'forum';
+                } else if (!this.message.isOutbox) {
+                    this.statusIcon = 'reply';
+                } else if (messageService.showStatusIcon(this.message, this.receiver)) {
+                    // Show status icon of incoming messages every thime
```
Comment (dbrgn) [inline src/directives/latest_message.ts]: thime -> time 🤓
