### PR TITLE
Hide input for blocked contacts

### LINKED ISSUE #462: Inconsistent error messages if you want to send message to blocked contact
## Expected Behavior
Consistent error message. I'd prefer the second screenshot.

## Current Behavior
Inconsistent error message.

## Steps to Reproduce (for bugs)
1. Connect to Threema Web
2. Block a contact in the smartphone app
3. Try to write a message to the blocked contact in Threema Web
4. You'll see this error message:
bildschirmfoto_2018-03-02_18-26-25
5. Close Threema Web session and reconnect
6. Now try to write a message to the blocked contact again
7. You'll see this error message:
bildschirmfoto_2018-03-02_18-25-03

## Your Environment
* Threema Web version: 1.8.2
* Threema for Android version: 3.4
* Browser name and version: Firefox 58.0.2

### PR DESCRIPTION
**Pull request by IndianaDschones**
Fixes #462

### CODE REVIEW

File: src/services/webclient.ts [hunk 1]
```diff
@@ -1002,9 +997,6 @@ export class WebClientService {
                         case 'file_too_large':
                             errorMessage = this.$translate.instant('error.FILE_TOO_LARGE');
                             break;
-                        case 'blocked':
-                            errorMessage = this.$translate.instant('error.CONTACT_BLOCKED');
-                            break;
```
Comment (sillych) [inline src/services/webclient.ts]: This condition must not be removed. Now you can drag'n drop a file into a chat view, the app return the "blocked" error.... please re-enable the condition (and the translations)

**Comment by dbrgn** [comment]
@IndianaDschones ping. are you still interested in finishing this PR?

**Comment by IndianaDschones** [comment]
@dbrgn Yeah still interested. But i totally forgot it. Sorry...
I´ve got a prototype with the requested changes, which i will push today. But i need your knowledge 💡 I´ll ask the question after i updated my branch - stay tuned 😉

File: src/directives/compose_area.ts [hunk 2]
```diff
@@ -93,6 +98,39 @@ export default [
                     toBytes?: number,
                 } = null;
 
+                let receiverBlocked: boolean = false;
+
+                // TODO objectEquality rausbekommen
+                scope.$watch(
```
Comment (IndianaDschones) [inline src/directives/compose_area.ts]: I only need to check/watch the "blocked" flag. My approach was similar to the one in avatar.ts. But the event wasn´t fired. To check if it would work, I enabled deep checking. And it works. But i want to get rid of the workaround. Can you give me some hints @dbrgn ?

Comment (dbrgn) [reply src/directives/compose_area.ts]: Hm, so this code here doesn't work if you remove the ", true" argument?

Comment (IndianaDschones) [reply src/directives/compose_area.ts]: Correct

Comment (dbrgn) [reply src/directives/compose_area.ts]: Try this:

```diff
diff --git a/src/directives/compose_area.ts b/src/directives/compose_area.ts
index 63cb937..e9ddc94 100644
--- a/src/directives/compose_area.ts
+++ b/src/directives/compose_area.ts
@@ -98,18 +98,6 @@ export default [
                     toBytes?: number,
                 } = null;
 
-                let receiverBlocked: boolean = false;
-
-                // TODO objectEquality rausbekommen
-                scope.$watch(
-                    () => scope.receiver,
-                    (newRec: threema.Receiver, oldRec: threema.Receiver) => {
-                    if (hasValue(newRec)) {
-                        receiverBlocked = receiverService.isBlocked(newRec);
-                        chatBlocked(receiverBlocked);
-                    }
-                }, true);
-
                 function chatBlocked(blocked: boolean) {
                     if (blocked) {
                         sendTrigger.removeClass(TRIGGER_ENABLED_CSS_CLASS);
@@ -131,6 +119,19 @@ export default [
                     }
                 }
 
+                // Initialize blocking state
+                chatBlocked(receiverService.isBlocked(scope.receiver));
+
+                // Watch `isBlocked` flag for changes
+                scope.$watch(
+                    (_scope) => receiverService.isBlocked(_scope.receiver),
+                    (isBlocked: boolean, wasBlocked: boolean) => {
+                        if (isBlocked !== wasBlocked) {
+                            chatBlocked(isBlocked);
+                        }
+                    },
+                );
+
                 /**
                  * Stop propagation of click events and hold htmlElement of the emojipicker
                  */
@@ -564,7 +565,7 @@ export default [
                 function onEmojiTrigger(ev: UIEvent): void {
                     ev.stopPropagation();
                     // TODO maybe simlify
-                    if (receiverBlocked) {
+                    if (receiverService.isBlocked(scope.receiver)) {
                         hideEmojiPicker();
                         return;
                     }
@@ -663,7 +664,7 @@ export default [
                 function onFileTrigger(ev: UIEvent): void {
                     ev.preventDefault();
                     ev.stopPropagation();
-                    if (receiverBlocked) {
+                    if (receiverService.isBlocked(scope.receiver)) {
                         return;
                     }
                     const input = element[0].querySelector('.file-input') as HTMLInputElement;
@@ -673,7 +674,7 @@ export default [
                 function onSendTrigger(ev: UIEvent): boolean {
                     ev.preventDefault();
                     ev.stopPropagation();
-                    if (receiverBlocked) {
+                    if (receiverService.isBlocked(scope.receiver)) {
                         return;
                     }
                     return sendText();
```

Unfortunately in AngularJS it's quite tricky to get data binding right :confused:

Comment (IndianaDschones) [reply src/directives/compose_area.ts]: Works like a charm :) Thanks 👍 
Unfortunately i´m unable to push to my branch atm. I´ll try to fix it over the weekend.

**Comment by IndianaDschones** [comment]
It should work in principle. One thing about the drag and drop feature: should it be disabled (would be quiet easy) or should it be enabled and some kind of dialog show up?

**Comment by IndianaDschones** [comment]
@dbrgn I think everything is ready to be merged - finally ;)
