### PR TITLE
Fix `sortKey` for temporary messages

### LINKED ISSUE #871: Messages not properly marked as read
## Bug Description

Occasionally messages received from a contact are not marked as read. The wrong message ID is sent (too low).

This only happens in Beta 4, not in Beta 3.

Code that marks messages as read can be found in `messenger.ts`.

### PR DESCRIPTION
**Pull request by lgrahl**
Resolves #871

### CODE REVIEW

File: src/threema/container.ts [hunk 1]
```diff
@@ -567,16 +567,31 @@ class Messages implements threema.Container.Messages {
...
+
+        // Append new messages
+        for (const message of messages) {
+            // Determine sort key (if not set)
+            // Note: This resolves an ugly interface violation of temporary
+            //       messages.
+            if (message.sortKey === undefined) {
+                message.sortKey = receiverMessages.list.length > 0
+                    ? receiverMessages.list[receiverMessages.list.length - 1].sortKey
+                    : 0;
```
Comment (dbrgn) [inline src/threema/container.ts]: Note that in theory the sort key of an actual message could be negative, since the field is just an integer.

Maybe `Number.MIN_SAFE_INTEGER`?

Alternatively update the ARP and state that values may not be negative.

Comment (lgrahl) [reply src/threema/container.ts]: The latter makes more sense to me.

Comment (lgrahl) [reply src/threema/container.ts]: https://github.com/threema-ch/app-remote-protocol/pull/6

**Comment by lgrahl** [comment]
@dbrgn Good to merge then?
