### PR TITLE
Fix fallback img for contacts without high-res avatar

### LINKED ISSUE #851: "Avatar icon" barely visible in profile page view
## Bug Description

In the chat list the "avatar icon" is shown:
Screenshot_2019-07-10 Threema Web(1)

In the profile page the "avatar icon" is barely visible, only the background color:
Screenshot_2019-07-10 Threema Web(2)

## Your Environment

* Threema Web version: Version 2.2.0-beta.3 Glärnisch
* Threema App version: 4.0-beta2 (Android)
* Browser name and version: Firefox 67.0.4

### PR DESCRIPTION
**Pull request by dbrgn**
- Use transparent SVG for high-res contact fallback image
- Only show low-res version in high-res container if loading is still in progress

Fixes #851.

### CODE REVIEW

File: src/directives/avatar.ts [hunk 1]
```diff
@@ -183,6 +182,7 @@ export default [
                         // Otherwise, if we requested a high res avatar but
                         // there is only a low-res version, show that.
                         if (this.highResolution
+                            && this.isLoading
```
Comment (dbrgn) [inline src/directives/avatar.ts]: This is the reason why the low-res version was displayed instead of the fallback.

File: src/directives/avatar.ts [hunk 2]
```diff
@@ -199,28 +199,31 @@ export default [
                             return;
                         }
 
+                        // We only want to load an avatar if the avatar is in view.
+                        //
+                        // To avoid having a lot of avatars being loaded when
+                        // just scrolling through a list of contacts, trigger
+                        // the avatar loading logic after a timeout. If the
+                        // avatar goes out of view again before the timeout has
+                        // elapsed, cancel the loading.
```
Comment (lgrahl) [inline src/directives/avatar.ts]: :+1: for the explainer
